.github/workflows/deploy.yml
What this PR does / why we need it:
这个PR添加了服务器更新部署工作流
=> ci：添加服务器更新部署工作流

service/group/config/config.yaml, service/msg/config/config.yaml, service/relation/config/config.yaml, service/user/config/config.yaml
What this PR does / why we need it:
这个PR修改各服务配置文件的mysql配置
=> fix(msg、relation、user、group服务): 修改各服务配置文件的mysql配置

.github/pull_request_template.md
=> chore(pr): 添加pr模板

deploy/docker/docker-compose.yaml, interface/gateway/Makefile, interface/group/Makefile, interface/msg/Makefile, interface/relation/Makefile, interface/user/Makefile, service/group/Makefile, service/msg/Makefile, service/relation/Makefile, service/user/Makefile
这个PR优化各服务的makefile、修改docker-compsoe配置
Fixes #
=> build(makefile、docker-comspoe): 优化makefile、修改docker-compsoe文件配置

Makefile, docs/group_docs.go, docs/group_swagger.json, docs/group_swagger.yaml, interface/group/server/http/group.go, interface/msg/server/http/msg.go, interface/user/server/http/http.go, interface/user/server/http/user.go, pkg/encryption/encryption.go, pkg/http/middleware/encryption_middleware.go, pkg/http/response/response.go, service/msg/domain/entity/group_message.go
=> feat(pkg):调整加解密中间件逻辑

interface/group/config/config.yaml.template, interface/msg/config/config.yaml.template, service/relation/domain/entity/user_group.go, service/relation/domain/entity/user_relation.go, service/user/domain/entity/user.go
这个pr为实体删除字段添加默认值，添加msg_bff group_bff配置文件信息
Fixes #
=> fix(msg_bff group_bff): 实体删除字段设置默认值，msg_bff group_bff添加配置文件信息

docs/msg_docs.go, docs/msg_swagger.json, docs/msg_swagger.yaml
=> docs(msg_bff): 更新msg swagger文档

.github/workflows/docker_gateway.yml
=> ci(gateway): 优化gateway的工作流

deploy/docker/config/interface/relation.yaml.template, interface/gateway/server/http/http.go, interface/relation/config/config.yaml.template
gateway添加storage代理，优化relation配置
Fixes #
=> fix(gateway): 添加storage代理，优化relation配置

deploy/docker/docker-compose.yaml, interface/storage/config/config.go, interface/storage/server/http/http.go, interface/storage/server/http/storage.go
docker-compose添加storage_svc
Fixes #
=> fix(storage_svc): docker-compose添加storage_svc

service/msg/infrastructure/persistence/db.go
=> feat(msg_svc): 添加Automigrate表

interface/user/server/http/user.go, pkg/http/response/response.go, pkg/utils/util.go
=> feat:添加hash密码

interface/msg/server/http/msg.go, interface/user/server/http/user.go
=> feat:新增获取对话列表排序

interface/relation/server/http/relation.go, interface/user/server/http/user.go, pkg/http/middleware/recovery_middleware.go
=> fix: 修复用户昵称为空时导致的panic

.github/workflows/docker_group_interface.yml, .github/workflows/docker_msg_interface.yml, .github/workflows/docker_relation_interface.yml, .github/workflows/docker_user_interface.yml
=> ci: pkg/http文件发生时改变触发构建

.github/workflows/docker_storage_interface.yml, .github/workflows/docker_storage_service.yml
=> ci: 添加storage服务工作流

deploy/docker/config/interface/storage.yaml.template
=> build: 修改compose storage配置模版

pkg/utils/usersorter/usersorter.go
=> fix(relation_bff): 修复获取好友列表内容为空时不返回字段的问题

deploy/docker/docker-compose.yaml, interface/msg/config/config.yaml.template, pkg/config/config.go
=> feat(msg_bff): 添加消息队列配置

deploy/docker/docker-compose.yaml
=> build(message_queue): docker-compose添加mq配置

deploy/docker/config/interface/group.yaml.template, deploy/docker/config/interface/msg.yaml.template, interface/msg/config/config.go
- 修改msg_bff遗留的config代码配置
- 完善配置文件模版
Fixes #
=> fix(msg_bff): 修改msg_bff遗留的config代码配置

.github/workflows/docker_gateway.yml, .github/workflows/docker_group_interface.yml, .github/workflows/docker_group_service.yml, .github/workflows/docker_msg_interface.yml, .github/workflows/docker_msg_service.yml, .github/workflows/docker_relation_interface.yml, .github/workflows/docker_relation_service.yml, .github/workflows/docker_storage_interface.yml, .github/workflows/docker_storage_service.yml, .github/workflows/docker_user_interface.yml, .github/workflows/docker_user_service.yml
=> ci: 优化工作流匹配条件

interface/storage/server/http/storage.go
=> feat(storage_bff): 添加文件上传大小限制

go.mod, go.sum, interface/msg/config/config.go, interface/msg/config/ws.go, interface/msg/server/http/http.go, interface/msg/server/http/msg.go, interface/relation/Makefile, interface/relation/config/config.go, interface/relation/server/http/http.go, interface/relation/server/http/relation.go, pkg/msg_queue/rabbit_mq.go
=> feat:添加离线消息推送

service/msg/infrastructure/persistence/msg_repository.go
=> fix:修复消息列表排序

interface/relation/config/config.yaml.template
=> chore(relation_bff): 添加消息队列配置

interface/msg/server/http/msg.go, pkg/msg_queue/rabbit_mq.go
=> fix:修复消息队列推送问题

pkg/code/code.go, pkg/code/common_code.go, pkg/code/svc_code.go, pkg/http/middleware/recovery_middleware.go, service/group/service/service.go, service/msg/service/dialog_service.go, service/msg/service/msg_service.go, service/relation/service/group_service.go, service/relation/service/user_service.go, service/storage/service/service.go, service/user/service/service.go
=> feat: 添加统一状态码

service/relation/service/user_service.go, service/user/service/service.go
=> fix(user_svc): 修复err为nil设置错误信息的panic

pkg/code/svc_code.go
=> fix(code): 添加缺少的关系服务状态码

service/msg/cmd/main.go, service/relation/cmd/main.go, service/relation/service/dialog_service.go
=> fix:完善todo，修改群聊信息、删除群聊

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml, interface/relation/server/http/http.go, interface/relation/server/http/relation.go
=> chore:更新api文档

interface/user/server/http/user.go
=> perf(user_bff): 优化获取用户信息逻辑

interface/relation/server/http/relation.go
=> perf(relation_bff): 优化关系服务接口逻辑

interface/msg/server/http/msg.go
=> fix:调整多个接口逻辑,用户申请加入群聊、同意群聊申请消息推送(50%)

service/user/service/service.go
=> fix:调整user-service用户注册接口

interface/relation/server/http/http.go, interface/relation/server/http/relation.go
=> fix:修复交换用户端到端公钥接口404的问题

interface/msg/server/http/msg.go, interface/relation/server/http/relation.go, interface/user/server/http/user.go, service/relation/service/user_service.go
=> fix(relation-service):调整添加好友接口

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/msg/config/ws.go, interface/relation/server/http/relation.go, service/relation/service/user_service.go
=> fix:调整管理好友请求接口逻辑

interface/msg/server/http/msg.go
=> fix:修改查询群聊所有用户id的rpc服务名称

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/server/http/relation.go
=> docs(relation): 更新relation swagger文档

service/relation/infrastructure/persistence/user_relation_repository.go
=> fix:查询好友关系语句按创建时间倒序

interface/msg/server/http/msg.go
=> fix:修改获取群聊的对话时返回群聊id

interface/relation/service/dtm_workflow.go, interface/relation/service/user.go
manageFriend接口引入dtm分布式事务
Fixes #
=> feat(relation): manageFriend接口引入dtm分布式事务

docs/msg_docs.go, docs/msg_swagger.json, docs/msg_swagger.yaml, interface/msg/api/model/model.go
=> fix:修复发送群聊消息参数问题

interface/relation/server/http/relation.go
=> fix:修复管理群聊申请用户id

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/api/model/model.go, interface/relation/server/http/relation.go
=> docs(lreation): 更新swagger文档

interface/relation/api/model/model.go
添加ManageFriendRequest action字段验证
Fixes #
=> feat(relation): 添加ManageFriendRequest action字段验证

interface/relation/api/model/model.go
=> fix:修复获取好友申请列表字段缺失

interface/relation/api/model/model.go, interface/relation/server/http/relation.go
=> feat(relation): 添加管理好友、群聊申请请求参数的验证方法

interface/relation/server/http/relation.go
=>  docs(relation): 添加对好友申请列表状态的表述

interface/relation/api/model/model.go
=> fix(relation): 修复由于action默认值

deploy/docker/docker-compose.yaml, interface/relation/server/http/relation.go, interface/relation/service/service.go, interface/relation/service/user.go, service/relation/infrastructure/persistence/user_relation_repository.go
=> feat(relation): 删除好友添加分布式事务

service/relation/infrastructure/persistence/user_relation_repository.go, service/relation/service/user_service.go
=> feat(relation): 删除好友时添加删除状态

interface/relation/server/http/relation.go, interface/relation/service/user.go
=> fix(relation): 修复推送消息到队列失败后不返回响应的错误

interface/relation/server/http/relation.go, interface/relation/service/group.go, service/relation/infrastructure/persistence/group_relation_repository.go, service/relation/service/group_service.go
=> feat(relation): 退出群聊添加分布式事务

service/group/infrastructure/persistence/group_repository.go
=> fix(group_svc): 删除群组后将状态设置为删除

service/storage/domain/entity/file.go, service/user/domain/entity/user.go
=> fix(storage,user): 修改deleted_at默认值

service/relation/service/dialog_service.go
=> fix(relation_svc): 创建群聊时没有把自己加入会话

interface/relation/server/http/http.go, interface/relation/server/http/relation.go, interface/relation/service/group.go, pkg/code/code.go, pkg/code/common_code.go, pkg/code/svc_code.go
=> feat(relation_bff): 优化InviteGroup错误提示

interface/relation/server/http/relation.go, interface/relation/service/group.go, pkg/code/svc_code.go
优化relation错误提示，删除多余注释代码
Fixes #
=> perf(relation_bff): 优化relation错误提示，删除多余注释代码

docs/group_docs.go, docs/group_swagger.json, docs/group_swagger.yaml, docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml
=> docs: 更新relation swagger文档

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/server/http/relation.go, service/relation/service/group_service.go
=> docs(relation): 更新swagger文档

interface/group/service/group.go, interface/group/service/service.go, service/relation/service/group_service.go
=> fix(relation): 创建群聊后添加对用户的推送

service/relation/service/dialog_service.go
=> fix(relation_svc): 修复创建群聊是没有为自己创建会话

pkg/utils/usersorter/usersorter.go, service/user/api/v1/user.pb.go, service/user/api/v1/user.proto
nick_name改成nickname
涉及接口：好友列表，登录，注册，获取用户信息，修改用户信息
Fixes #
=> fix(msg)：nick_name改成nickname

interface/storage/server/http/http.go, interface/user/api/model/model.go, interface/user/config/config.yaml.template, interface/user/server/http/http.go, interface/user/server/http/user.go, pkg/code/code.go, service/relation/service/user_service.go
=> perf(user): 优化获取用户信息

docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml
=> docs(user): 更新swagger文档

deploy/docker/config/interface/gateway.yaml.template, deploy/docker/config/interface/group.yaml.template, deploy/docker/config/interface/msg.yaml.template, deploy/docker/config/interface/relation.yaml.template, deploy/docker/config/interface/storage.yaml.template, deploy/docker/config/interface/user.yaml.template
=> build(compose): 更新模版配置

docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml, interface/user/server/http/http.go, interface/user/server/http/user.go, pkg/code/common_code.go
=> feat(user): 添加搜索用户信息接口和更新接口文档

deploy/docker/config/interface/gateway.yaml.template, deploy/docker/config/interface/msg.yaml.template, deploy/docker/config/interface/relation.yaml.template, interface/gateway/config/config.yaml.template, interface/msg/config/config.yaml.template, interface/relation/config/config.yaml.template
=> perf(config): 优化所有服务的配置文件

interface/msg/config/config.yaml.template, interface/user/config/config.yaml.template, service/msg/infrastructure/persistence/msg_repository.go, service/msg/service/msg_service.go, service/relation/service/dialog_service.go, service/relation/service/user_service.go
=> fix:优化现有本地事务

deploy/docker/docker-compose.yaml, interface/user/Makefile, interface/user/api/model/model.go, interface/user/cmd/main.go, interface/user/config/config.go, interface/user/config/config.yaml.template, interface/user/server/http/http.go, interface/user/server/http/user.go, interface/user/service/service.go, interface/user/service/user.go, pkg/code/svc_code.go, pkg/config/config.go, pkg/discovery/consul.go, pkg/discovery/discovery.go, service/relation/cmd/main.go, service/relation/service/service.go, service/user/Makefile, service/user/cmd/main.go, service/user/config/config.go, service/user/service/service.go
=> feat(user): 添加自定义Discovery接口、添加服务注册发现，分离http接口和业务代码

docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml, interface/user/api/model/model.go, interface/user/server/http/http.go, interface/user/server/http/user.go, interface/user/service/user.go, pkg/cache/redis.go, pkg/code/svc_code.go
=> feat:添加获取用户已登录客户端信息接口

interface/msg/server/http/http.go, interface/msg/server/http/msg.go, pkg/auth/auth.go
=> fix:调整token校验逻辑

pkg/http/middleware/auth_middleware.go, service/msg/api/v1/msg.proto
=> fix:调整ws链接逻辑

service/relation/infrastructure/persistence/group_relation_repository.go, service/relation/service/group_service.go
=> fix:调整查询用户群聊关系sql

interface/msg/service/service.go, interface/msg/service/user.go, interface/user/server/http/user.go, interface/user/service/service.go, interface/user/service/user.go, pkg/cache/redis.go
=> fix:完善退出登录逻辑

deploy/docker/docker-compose.yaml, interface/user/service/service.go
=> feat: 为所有服务添加consul配置中心

interface/relation/api/model/model.go, interface/relation/server/http/relation.go, interface/relation/service/group.go
=> fix:调整获取群聊成员接口逻辑，响应添加成员身份字段

service/relation/cmd/main.go
=> fix:修复未实现群聊申请服务的问题

interface/gateway/server/http/http.go, service/relation/cmd/main.go
=> fix(gateway relation_svc): 修复官网无法获取bff服务地址、relation未注册userFriend服务

docs/group_docs.go, docs/group_swagger.json, docs/group_swagger.yaml, docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/server/http/relation.go
=> fix:优化群聊移除用户接口逻辑

interface/group/server/http/group.go, interface/msg/server/http/msg.go, interface/msg/service/group.go, interface/msg/service/service.go, service/msg/service/msg_service.go
=> fix:修改删除群聊参数名称，修复msg加密未设置

interface/relation/service/user.go
feat:注册时生成随机头像
fix:修复添加好友时推送失败问题
Fixes #
=> fix:修复管理好友请求时推送失败问题

interface/storage/cmd/main.go
=> fix:优化项目启动时中间件校验逻辑

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, docs/storage_docs.go, docs/storage_swagger.json, docs/storage_swagger.yaml, interface/storage/api/model/model.go, interface/storage/server/http/http.go, interface/storage/server/http/storage.go, pkg/storage/minio/minio.go, pkg/storage/storage.go
=> feat:添加分片上传文件接口

service/msg/service/msg_service.go
=> fix:修复获取对话列表时没返回最后一条消息的发送者id

deploy/docker/docker-compose.yaml, interface/storage/server/http/http.go, interface/user/service/service.go, interface/user/service/user.go
=> fix:修复注册时生成头像无法展示问题

deploy/docker/docker-compose.yaml
=> chore(compose): 修改live容器名称

interface/live/server/http/http.go
=> feat(live): 添加enc

.github/workflows/docker_live_interface.yml
=> ci(live): 添加live工作流

interface/gateway/server/http/http.go
=> perf(gateway): 优化错误响应

interface/live/config/config.yaml.template, interface/live/service/user.go
=> fix(live): 优化空闲时间格式

interface/group/server/http/group.go, interface/group/service/group.go, interface/msg/api/model/ws.go, interface/msg/service/user.go, service/relation/service/group_service.go
=> fix:修复创建群聊时无法邀请成员

interface/msg/api/model/ws.go, interface/msg/service/group.go
=> fix:优化推送群聊ws消息字段

Makefile, docs/live_docs.go, docs/live_swagger.json, docs/live_swagger.yaml, go.mod, go.sum, interface/group/server/http/http.go, interface/live/Makefile, interface/live/api/dto/group.go, interface/live/api/dto/user.go, interface/live/api/model/redis.go, interface/live/server/http/group.go, interface/live/server/http/http.go, interface/live/server/http/user.go, interface/live/service/group.go, interface/live/service/service.go, interface/live/service/user.go, interface/msg/config/ws.go, interface/msg/server/http/http.go, interface/relation/server/http/http.go, interface/storage/server/http/http.go, interface/user/server/http/http.go, pkg/cache/redis.go, pkg/code/svc_code.go, pkg/db/migrations/cmd/root.go
- 添加拒绝拒绝通话
- 优化dto
- 优化redis中的room存储信息
- 添加对应的websocket事件
Fixes #
=> feat(live_user): 优化用户通话服务

service/msg/domain/entity/group_message.go, service/msg/infrastructure/persistence/msg_repository.go
=> fix:修复发送群聊消息时无法@用户

docs/msg_docs.go, docs/msg_swagger.json, docs/msg_swagger.yaml, docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/server/http/relation.go, service/relation/service/user_service.go
=> fix:修复无法拉黑用户

interface/user/service/user.go
=> perf(user_bff): 优化用户登录失败错误提示

docs/live_docs.go, docs/live_swagger.json, docs/live_swagger.yaml, interface/live/api/dto/group.go, interface/live/api/dto/user.go, interface/live/config/config.yaml.template, interface/live/server/http/group.go, interface/live/server/http/http.go, interface/live/server/http/user.go, interface/live/service/group.go, interface/live/service/service.go, interface/live/service/user.go, interface/msg/config/ws.go, pkg/http/middleware/recovery_middleware.go
=> feat(live_group): 添加群聊通话接受拒绝和优化用户通话

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/api/model/model.go, interface/relation/server/http/relation.go
=> docs(relation): 更新群聊申请列表响应状态描述

interface/live/service/user.go
=> fix(live_bff): 修改生成通话tokenbug

interface/live/config/config.yaml.template
=> chore(live): 修改live通话空闲时间

docs/live_docs.go, docs/live_swagger.json, docs/live_swagger.yaml, interface/live/server/http/group.go, interface/live/service/group.go
=> docs(live): 更新swagger文档

docs/live_docs.go, docs/live_swagger.json, docs/live_swagger.yaml, interface/live/api/dto/group.go, interface/live/api/dto/user.go, interface/live/api/model/redis.go, interface/live/server/http/group.go, interface/live/server/http/user.go, interface/live/service/group.go, interface/live/service/user.go
=> fix(live_group): 退出通话redis没有删除对应key

interface/msg/service/user.go, interface/user/server/http/user.go, interface/user/service/user.go, pkg/auth/auth.go, pkg/cache/redis.go
=> fix:优化redis登录限制

interface/live/service/user.go
=> perf(live_user): 优化用户通话redis存储结构

interface/live/api/model/redis.go, interface/live/service/group.go, interface/live/service/user.go
=> perf(live): 优化代码逻辑和变量命名

interface/live/server/http/user.go, interface/live/service/user.go
=> perf(live): 优化创建通话逻辑

docs/live_docs.go, docs/live_swagger.json, docs/live_swagger.yaml, interface/live/api/dto/group.go, interface/live/api/dto/user.go, interface/live/server/http/group.go, interface/live/server/http/user.go, interface/live/service/group.go, interface/live/service/user.go
=> perf(live): 更新创建通话后获取token逻辑

interface/live/server/http/user.go, interface/live/service/group.go, interface/live/service/user.go
=> perf(live): 优化token生成

interface/relation/service/user.go, service/relation/service/user_friend_request_service.go, service/relation/service/user_service.go
=> fix:优化添加好友请求逻辑

docs/group_docs.go, docs/group_swagger.json, docs/group_swagger.yaml, docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml, interface/user/api/model/model.go, interface/user/server/http/http.go, interface/user/server/http/user.go, interface/user/service/user.go, pkg/code/svc_code.go, pkg/utils/util.go
=> feat(user):添加使用邮箱重置pgp秘钥功能

interface/msg/api/model/ws.go, interface/msg/config/ws.go, interface/msg/server/http/msg.go, interface/msg/service/client.go, interface/msg/service/group.go, interface/msg/service/user.go, pkg/cache/redis.go
=> feat:添加用户上下线状态更新

interface/relation/service/user.go
=> fix:修复无法添加好友

interface/msg/api/model/ws.go, interface/msg/service/client.go, interface/msg/service/user.go
=> fix:修复发送私聊消息时无法推送给自己

interface/msg/service/client.go
=> fix:修改ws上线推送好友状态事件

interface/live/cmd/main.go, interface/live/config/config.go, interface/live/config/config.yaml.template, interface/live/server/http/http.go, interface/live/service/service.go
=> feat(live): live服务使用manager启动

interface/msg/cmd/main.go, interface/msg/config/config.go, interface/msg/server/http/http.go, interface/msg/server/http/msg.go, interface/msg/service/service.go, interface/msg/service/user.go
=> feat(msg_bff): msg服务使用manager启动

interface/relation/cmd/main.go, interface/relation/config/config.go, interface/relation/config/config.yaml.template, interface/relation/server/http/http.go, interface/relation/server/http/relation.go, interface/relation/service/service.go
=> feat(relation_bff): relation服务使用manager启动

interface/storage/cmd/main.go, interface/storage/config/config.go, interface/storage/server/http/http.go, interface/storage/server/http/storage.go, pkg/server/http.go
=> feat(storage_bff): storage服务使用manager启动

interface/msg/config/config.yaml.template, interface/relation/config/config.yaml.template, interface/storage/config/config.yaml.template, interface/user/cmd/main.go, interface/user/config/config.go, interface/user/config/config.yaml.template, interface/user/server/http/http.go, interface/user/server/http/user.go, interface/user/service/service.go, interface/user/service/user.go, pkg/discovery/consul.go, pkg/server/http.go
=> feat(user_bff): user服务使用manager启动

service/group/config/config.yaml.template, service/msg/cmd/main.go, service/msg/config/config.yaml.template, service/msg/service/service.go, service/relation/cmd/main.go, service/relation/config/config.yaml.template, service/relation/service/service.go, service/storage/cmd/main.go, service/storage/config/config.yaml.template, service/storage/service/service.go, service/user/cmd/main.go, service/user/config/config.go, service/user/config/config.yaml.template, service/user/service/service.go
=> feat(svcs): 所有grpc服务使用manager管理

pkg/manager/manager.go
=> perf(manager): 如果没有设置健康检查就先忽略

interface/group/service/service.go, interface/live/service/service.go, interface/msg/service/service.go, interface/relation/service/service.go, interface/storage/server/http/http.go, interface/user/service/service.go, pkg/server/grpc.go, pkg/server/http.go
=> fix(manager): 修复直连时未生成客户连接，修改处理初始化客户端时匹配的服务名称

go.mod, go.sum, interface/group/cmd/main.go, interface/live/cmd/main.go, interface/msg/cmd/main.go, interface/relation/cmd/main.go, interface/storage/cmd/main.go, interface/user/cmd/main.go, interface/user/server/http/http.go, interface/user/service/service.go, pkg/server/http.go, service/group/cmd/main.go, service/msg/cmd/main.go, service/relation/cmd/main.go, service/storage/cmd/main.go, service/user/cmd/main.go
fix(flag): 修改所有服务的健康检查端口
Fixes #
=> fix(user_bff): 修复Handler方法没有使用指针类型导致的panic

service/user/service/service.go
=> fix:修复无法登录问题

interface/live/service/user.go, interface/msg/config/ws.go
=> fix(live): 修复判断用户是否在通话中的逻辑，添加通话接受事件

interface/relation/api/model/model.go
=> feat（relation_bff）:设置私聊，群聊静默通知接口请求体修改

service/relation/infrastructure/persistence/dialog_repository.go
=> fix:修复查询对话列表时数据错误

interface/msg/api/model/model.go, interface/msg/service/user.go
=> fix(msg_bff):调整获取对话落后消息响应参数

interface/msg/service/user.go
=> fix(msg_bff):修复获取对话落后消息响应数据错误

service/user/infrastructure/persistence/user_login_repository.go
=> fix(user_serivce):修复登录后user_login表对应token未更新

Makefile, admin/config/config.yaml, interface/msg/service/group.go, interface/msg/service/user.go
=> fix(msg_bff):修复编辑消息后推送的消息内容不是最新的

interface/msg/service/group.go, interface/relation/api/model/model.go
=> fix(relation_bff): 修复标注群聊消息推送时标注状态错误，修复设置免打扰时参数验证失败问题

interface/live/api/dto/group.go, interface/live/config/config.yaml.template
=> fix(live): 修复拒绝群聊通话参数验证失败

interface/gateway/cmd/main.go, interface/gateway/server/http/http.go
=> refactor(gateway): 使用manager启动

pkg/encryption/encryption_test.go
=> fix(test): 修复test文件导致的构建超时

interface/msg/service/service.go, interface/msg/service/user.go, pkg/utils/util.go, service/user/service/user_login_service.go
=> fix(user_service): 修复获取用户登录信息没有返回相应信息导致推送失败

interface/msg/service/user.go, pkg/constants/user.go
=> fix:优化给系统账号发送消息时推送逻辑

docs/msg_docs.go, docs/msg_swagger.json, docs/msg_swagger.yaml, docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/msg/api/model/model.go
=> refactor(msg_bff): 修改GroupMessageReadRequest的MsgIds请求字段

docs/relation_docs.go, docs/relation_swagger.json, docs/relation_swagger.yaml, interface/relation/api/model/model.go, interface/relation/server/http/http.go, interface/relation/server/http/relation.go, interface/relation/service/group.go
=> feat(relation_bff):添加获取群公告详情

interface/storage/cmd/main.go, interface/user/server/http/user.go, pkg/storage/minio/minio.go
=> fix(storage_pkg):修改预共享url过期时间

interface/relation/api/model/model.go, interface/relation/service/group.go, interface/storage/config/config.yaml.template, interface/storage/server/http/http.go, interface/user/config/config.yaml.template, interface/user/service/service.go, pkg/config/config.go, service/msg/infrastructure/persistence/msg_repository.go
=> fix(msg_service):修复对话列表无法查询群聊最后一条消息

deploy/docker/docker-compose.yaml, interface/user/service/user.go, pkg/storage/minio/minio.go, service/relation/infrastructure/persistence/group_announcement_read_repository.go
=> fix(relation_service):修复已读公告后再次已读会添加新记录

deploy/docker/docker-compose.yaml, interface/storage/server/http/http.go, interface/storage/server/http/storage.go, interface/user/service/user.go, pkg/utils/http/http.go
=> fix:修复minio无法启动

deploy/docker/docker-compose.yaml, docs/group_docs.go, docs/group_swagger.json, docs/group_swagger.yaml, interface/group/server/http/group.go, service/group/infrastructure/persistence/group_repository.go
=> fix:无法修改群聊信息

Makefile, interface/live/server/http/group.go, interface/msg/service/group.go, interface/msg/service/user.go, interface/relation/server/http/http.go, interface/relation/service/group.go
=> fix(msg): 修复自己发送的信息未设置为已读

interface/msg/api/model/model.go, interface/msg/service/group.go, interface/msg/service/user.go
=> fix(msg): 调整获取私聊、群聊消息列表响应参数

interface/msg/service/user.go
=> fix:获取对话列表时发送者信息字段为空

interface/msg/api/model/model.go, interface/msg/service/group.go
=> fix:修复获取群聊消息时消息没有已读时间

interface/gateway/server/http/http.go
=> fix:修复gateway日志服务无法启动

pkg/config/config.go, pkg/db/mysql.go, pkg/http/middleware/logger_middleware.go, pkg/manager/manager.go, service/group/config/config.yaml.template, service/group/service/service.go, service/msg/config/config.yaml.template, service/msg/service/service.go, service/relation/config/config.yaml.template, service/relation/service/service.go, service/storage/config/config.yaml.template, service/storage/service/service.go, service/user/config/config.yaml.template, service/user/service/service.go
=> fix:优化service日志逻辑

pkg/config/config.go
=> fix(config): 修复本地获取配置文件函数

pkg/config/config.go, pkg/discovery/consul.go
=> fix(config): 修复由于yaml库版本不一致导致的解析配置失败

pkg/config/config.go
=> fix(config): 修复加载配置逻辑

interface/group/service/group.go, interface/msg/config/config.yaml.template, interface/user/service/user.go, pkg/config/config.go, pkg/storage/minio/minio.go, pkg/storage/storage.go, service/user/service/service.go
=> fix:修复注册用户分布式事务无效问题，修复注册后头像url会过期

admin/server/http/http.go, go.mod, interface/group/server/http/http.go, interface/live/server/http/http.go, interface/live/service/group.go, interface/live/service/service.go, interface/live/service/user.go, interface/msg/api/model/model.go, interface/msg/server/http/http.go, interface/msg/service/client.go, interface/msg/service/service.go, interface/msg/service/user.go, interface/relation/server/http/http.go, interface/storage/server/http/http.go, interface/user/server/http/http.go, interface/user/service/service.go, interface/user/service/user.go, pkg/auth/auth.go, pkg/cache/redis.go, pkg/http/middleware/admin_middleware.go, pkg/http/middleware/auth_middleware.go
=> fix:优化获取用户对话列表逻辑

interface/user/api/model/model.go, interface/user/service/user.go
=> fix:调整获取好友信息接口响应参数

pkg/db/mysql.go
=> fix:修复每次请求都新建数据库连接

.github/workflows/docker_admin.yml, .github/workflows/docker_gateway.yml, .github/workflows/docker_group_interface.yml, .github/workflows/docker_group_service.yml, .github/workflows/docker_msg_interface.yml, .github/workflows/docker_msg_service.yml, .github/workflows/docker_relation_interface.yml, .github/workflows/docker_relation_service.yml, .github/workflows/docker_storage_interface.yml, .github/workflows/docker_storage_service.yml, .github/workflows/docker_user_interface.yml, .github/workflows/docker_user_service.yml
=> ci(action): 更新工作流匹配条件

interface/msg/service/group.go, interface/relation/service/group.go, interface/relation/service/user.go, pkg/code/svc_code.go, pkg/utils/usersorter/usersorter.go
=> feat:获取好友列表，群聊列表添加缓存

pkg/config/config.go
=> fix(config): 修改因为yaml标签错误导致的配置解析为空

interface/msg/service/user.go, service/msg/service/msg_service.go
=> fix:修复获取私聊消息列表时对话id为空,修复进行多个已读消息操作时并发问题

admin/service/service.go, interface/group/api/model/model.go, interface/group/service/group.go, interface/group/service/service.go, interface/msg/api/model/model.go, interface/msg/api/model/ws.go, interface/msg/service/client.go, interface/msg/service/user.go, interface/relation/service/group.go, interface/relation/service/user.go, interface/storage/cmd/main.go, interface/user/service/user.go, pkg/cache/redis.go, service/user/service/service.go
=> fix:修复添加好友后缓存不更新对话，修复创建群聊，删除群聊后缓存不更新

interface/group/service/group.go, interface/msg/service/user.go, service/relation/service/group_service.go
=> fix:修复解散群聊对话未更新

admin/server/http/http.go, admin/service/service.go
=> fix:优化admin初始化逻辑

interface/live/service/user.go
=> fix(live): 修复redis扫描函数提前结束的问题

interface/live/service/group.go
=> fix(live): 修复创建通话时没有先将成员加入方便后续的推送

interface/group/service/group.go, interface/msg/service/group.go, interface/msg/service/user.go, interface/relation/service/group.go, interface/relation/service/user.go, pkg/cache/redis.go
=> fix:优化缓存逻辑

docs/user_docs.go, docs/user_swagger.json, docs/user_swagger.yaml, interface/user/server/http/http.go, interface/user/server/http/user.go, interface/user/service/user.go
=> feat:添加修改用户头像接口

docs/group_docs.go, docs/group_swagger.json, docs/group_swagger.yaml, interface/group/config/config.yaml.template, interface/group/server/http/group.go, interface/group/server/http/http.go, interface/group/service/group.go, interface/group/service/service.go, interface/relation/service/user.go, interface/user/server/http/user.go, interface/user/service/user.go
=> feat:添加修改群聊头像接口

deploy/docker/config/interface/group.yaml.template, deploy/docker/config/interface/msg.yaml.template, deploy/docker/config/interface/relation.yaml.template, deploy/docker/config/interface/user.yaml.template, deploy/docker/config/service/group.yaml.template, deploy/docker/config/service/msg.yaml.template, deploy/docker/config/service/relation.yaml.template, deploy/docker/config/service/storage.yaml.template, deploy/docker/config/service/user.yaml.template, interface/group/config/config.yaml.template, interface/group/service/group.go, interface/group/service/service.go, interface/live/config/config.yaml.template, interface/msg/config/config.yaml.template, interface/msg/service/group.go, interface/msg/service/service.go, interface/msg/service/user.go, interface/relation/config/config.yaml.template, interface/relation/service/group.go, interface/relation/service/service.go, interface/relation/service/user.go, interface/user/config/config.yaml.template, interface/user/service/service.go, interface/user/service/user.go, pkg/config/config.go, service/group/config/config.yaml.template, service/msg/config/config.yaml.template, service/relation/config/config.yaml.template, service/storage/config/config.yaml.template, service/user/config/config.yaml.template
=> feat:添加缓存开关配置

interface/live/service/group.go, pkg/code/svc_code.go
=> fix(live): 修复拒绝通话校验逻辑

interface/live/service/user.go
=> fix(live): 修复用户通话未校验双方好友关系

interface/live/api/model/redis.go, interface/live/service/group.go
=> fix(live): 修复群聊通话拒绝时未给参与者推送通话拒绝事件

interface/storage/server/http/storage.go
=> fix(storage): 修复上传接口返回url不正常

interface/live/api/dto/group.go, interface/live/api/dto/user.go, interface/live/api/model/redis.go, interface/live/server/http/group.go, interface/live/server/http/user.go, interface/live/service/group.go, interface/live/service/service.go, interface/live/service/user.go, pkg/http/middleware/recovery_middleware.go
=> perf(live): 优化live创建、结束通话逻辑，优化redis通话存储结构

interface/storage/api/model/model.go, interface/storage/server/http/http.go
=> fix(storage): 修复服务名称错误导致的空指针，添加文件类型

admin/cmd/main.go, admin/service/service.go, interface/group/cmd/main.go, interface/group/service/service.go, interface/storage/cmd/main.go, interface/storage/server/http/http.go, interface/user/cmd/main.go, interface/user/service/service.go, pkg/config/config.go, pkg/discovery/consul.go, pkg/manager/manager.go
=> fix(storage admin user group ): 修复服务名称错误导致的空指针，添加文件类型，添加获取配置文件逻辑

admin/cmd/main.go, interface/group/cmd/main.go, interface/storage/server/http/http.go, interface/user/cmd/main.go
=> fix(storage admin group): 修复获取配置文件逻辑

pkg/server/grpc.go, pkg/server/http.go
=> fix(manager): 修复服务停止时未取消注册的服务

service/storage/api/v1/storage.pb.go
=> fix:优化存储大小限制

admin/service/admin.go, interface/storage/server/http/http.go, interface/storage/server/http/storage.go, pkg/http/middleware/auth_middleware.go, pkg/storage/minio/minio.go
=> fix:调整系统账号默认头像生成逻辑，调整存储桶默认策略

interface/relation/service/user.go, interface/user/service/user.go, service/msg/service/msg_service.go, service/relation/infrastructure/persistence/dialog_repository.go, service/relation/infrastructure/persistence/user_relation_repository.go, service/relation/service/dialog_service.go
=> fix:修复删除好友事务回滚问题

internal/admin/service/service.go
=> fix:调整admin默认头像路径逻辑

deploy/docker/config/service/group.yaml.template, deploy/docker/docker-compose.yaml, interface/gateway/server/http/http.go, internal/group/cmd/main.go
=> fix:调整docker-compose文件group服务相关配置

internal/group/cmd/main.go, pkg/config/config.go, pkg/server/grpc.go, pkg/server/http.go
=> fix(manager config): 修复合并服务时无法进行正常的服务注册发现

internal/group/service/group.go
=> fix:调整获取对话列表，获取消息逻辑

internal/relation/cmd/main.go
=> fix:修复relation启动无法读取到公共配置文件

.github/workflows/docker_admin.yml, .github/workflows/docker_gateway.yml, .github/workflows/docker_group_service.yml, .github/workflows/docker_live_service.yml, .github/workflows/docker_msg_service.yml, .github/workflows/docker_relation_service.yml, .github/workflows/docker_storage_service.yml, .github/workflows/docker_user_service.yml
=> ci: 更新合并服务后的工作流

internal/admin/cmd/main.go, internal/admin/config/config.yaml, internal/admin/service/admin.go, internal/group/cmd/main.go, internal/msg/service/service.go, internal/storage/cmd/main.go, internal/user/service/user.go
=> fix:调整系统通知ws推送逻辑

internal/relation/service/user.go
=> fix:修复添加好友后好友列表显示错误

internal/admin/service/admin.go, internal/group/service/group.go, internal/msg/service/group.go, internal/msg/service/user.go, internal/relation/service/user.go, internal/user/service/user.go
=> fix:优化使用dtm事务逻辑

internal/relation/service/group.go
=> fix:修复无法加入群聊

internal/msg/api/http/model/model.go, internal/msg/domain/entity/user_message.go, internal/msg/interface/http/msg.go, internal/msg/service/group.go, internal/msg/service/user.go, internal/user/service/user.go
=> fix:调整标注、撤回消息逻辑

deploy/docker/docker-compose.yaml
=> chore(compose): 优化compose

cmd/admin/main.go, cmd/live/main.go
=> perf: 优化加载服务的配置文件路径

cmd/gateway/main.go, deploy/docker/docker-compose.yaml
=> perf: 优化compose

internal/msg/api/http/model/model.go, internal/msg/domain/entity/user_message.go, internal/msg/infrastructure/persistence/msg_repository.go, internal/msg/interface/grpc/msg_grpc.go, internal/msg/service/group.go, internal/msg/service/user.go, internal/relation/api/http/model/model.go, internal/relation/interface/http/http.go, internal/relation/service/user.go, internal/user/service/user.go
=> fix:修复修改好友备注后缓存没更新

internal/live/service/group.go, internal/live/service/user.go, pkg/cache/redis.go, pkg/constants/ws.go
=> fix: 修复通话服务加入离开逻辑，添加用户离开群聊通话事件

pkg/server/http.go
=> perf(manager): manager服务发现修改为非阻塞

internal/relation/interface/http/dialog.go, internal/relation/interface/http/group.go, internal/relation/interface/http/user.go
=> perf(live): 优化relationhttp接口结构

pkg/utils/util.go
=> build: 重新构建所有服务

cmd/live/main.go
=> fix:调整生成api文档逻辑

internal/msg/api/http/model/ws.go
=> fix:修改发送消息推送逻辑

internal/relation/infrastructure/persistence/user_friend_request_repository.go, internal/relation/interface/grpc/user_friend_request_grpc.go, internal/relation/interface/http/group.go, internal/relation/interface/http/user.go, internal/relation/service/user.go
=> perf(relation): 优化删除好友申请记录逻辑

internal/live/service/group.go, internal/live/service/user.go
=> perf(live): 优化通话token生成

internal/msg/domain/entity/user_message.go, internal/msg/service/group.go, internal/msg/service/user.go
=> fix:调整标注、撤回消息推送内容

cmd/admin/main.go, cmd/gateway/main.go, cmd/group/main.go, cmd/live/main.go, cmd/msg/main.go, cmd/relation/main.go, cmd/storage/main.go, cmd/user/main.go
=> perf: 为所有服务添加热重载、配置key启动参数

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/group/api/http/model/model.go, internal/msg/api/grpc/v1/msg.pb.go, internal/msg/api/grpc/v1/msg.proto, internal/msg/api/http/model/model.go, internal/msg/api/http/model/ws.go, internal/msg/interface/grpc/msg_grpc.go, internal/msg/service/group.go, internal/msg/service/user.go, internal/relation/api/http/model/model.go, internal/relation/service/dialog.go, pkg/constants/ws.go
=> fix:统一replay_id改为reply_id

internal/msg/service/group.go, internal/msg/service/user.go, pkg/code/svc_code.go
=> fix:修复取消标注事件未修改

go.mod, pkg/manager/internal.go
=> chore: 重新构建

pkg/manager/internal.go
=> feat(manager): 添加metrics

cmd/admin/main.go
=> fix:修复admin启动时没获取dtm配置

cmd/admin/main.go, cmd/gateway/main.go, cmd/group/main.go, cmd/live/main.go, cmd/msg/main.go, cmd/relation/main.go, cmd/storage/main.go, cmd/user/main.go, internal/admin/interface/http/http.go, internal/group/interface/http/http.go, internal/live/interface/http/http.go, internal/msg/interface/http/http.go, internal/relation/interface/http/http.go, internal/storage/interface/http/http.go, internal/user/interface/http/http.go
=> docs(swagger): 删除swagger对外接口

internal/msg/api/http/model/model.go, internal/msg/service/group.go, internal/msg/service/user.go, internal/user/service/user.go
=> fix:调整发送消息时响应内容

internal/msg/api/http/model/ws.go, internal/msg/service/group.go, internal/msg/service/user.go
=> fix:修复无法标注对方消息

internal/msg/service/group.go, internal/msg/service/user.go
=> fix:修复撤回消息失败

internal/storage/interface/http/http.go
=> fix:关闭文件访问校验

internal/user/api/http/model/model.go, internal/user/service/user.go
=> fix:退出登录请求参数login_number设为必填

internal/user/service/service.go, internal/user/service/user.go
=> perf(user): 优化使用自身grpc接口

internal/storage/service/service.go, internal/storage/service/storage.go
=> perf(storage): 优化使用自身grpc接口

internal/relation/service/user.go
=> fix(relation):修复添加黑名单，取消黑名单，设置阅后即焚，设置阅后即焚时间未更新缓存

internal/msg/service/group.go, internal/msg/service/service.go, internal/msg/service/user.go
=> perf(msg): 优化使用自身grpc接口

internal/live/service/group.go, internal/live/service/service.go, internal/live/service/user.go
=> style(live): 优化命名

internal/group/interface/http/http.go, internal/group/service/group.go, internal/group/service/service.go
=> perf(group): 优化使用自身grpc接口

internal/msg/service/group.go, internal/msg/service/user.go
=> fix(msg):调整编辑消息推送参数

internal/msg/service/service.go
=> fix(msg): 修复msgGroupService为赋值导致的空指针

internal/relation/infrastructure/persistence/user_relation_repository.go
=> pref(relation): 优化获取好友关系查询条件

internal/relation/service/service.go
=> fix(relation): 修复未赋值内部grpc服务导致的空指针

internal/msg/service/user.go, internal/user/service/user.go
=> fix(msg):调整发送消息推送逻辑

internal/live/interface/http/group.go, internal/live/interface/http/user.go, internal/live/service/group.go, internal/live/service/user.go
=> feat(live): 接受后的推送添加driverId

internal/admin/service/admin.go, internal/admin/service/service.go, internal/gateway/server/http/http.go, internal/group/interface/http/http.go, internal/group/service/group.go, internal/group/service/service.go, internal/live/service/service.go, internal/msg/service/group.go, internal/msg/service/service.go, internal/msg/service/user.go, internal/relation/service/group.go, internal/relation/service/service.go, internal/relation/service/user.go, internal/user/service/service.go, pkg/discovery/consul.go, pkg/discovery/discovery.go, pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> feat(discovery manager): 添加对服务的注册发现的KeepAlive

pkg/manager/server/http.go
=> perf(discovery manager): 删除服务发现重试机制

pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> perf(discovery manager): 优化grpc的服务发现注册逻辑添加KeepAlive

go.mod, go.sum, internal/admin/service/service.go, internal/gateway/server/http/http.go, internal/group/service/service.go, internal/live/service/service.go, internal/msg/service/service.go, internal/relation/service/service.go, internal/user/service/service.go
=> perf: 优化服务初始化客户端逻辑

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/relation/interface/http/group.go, internal/relation/interface/http/http.go, internal/relation/interface/http/user.go
=> fix(msg):调整删除好友申请和群聊申请路由定义

internal/relation/service/user.go, internal/user/service/user.go
=> fix(user):修复无法查询删除的好友用户信息

internal/admin/service/service.go, internal/gateway/server/http/http.go, internal/group/service/service.go, internal/live/service/service.go, internal/msg/service/service.go, internal/relation/service/service.go, internal/storage/interface/http/http.go, internal/user/service/service.go, pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> fix(manager discovery): 修复未释放资源导致的资源占用

pkg/discovery/consul.go, pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> fix(manager): 修复manager服务注册发现的KeepAlive导致的内存泄漏

cmd/admin/main.go, cmd/gateway/main.go, cmd/group/main.go, cmd/live/main.go, cmd/msg/main.go, cmd/relation/main.go, cmd/storage/main.go, cmd/user/main.go
=> feat(pprof): 为所有服务添加pprof

pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> chore: 删除多余打印

pkg/discovery/consul.go
=> pref(discovery): 优化配置watch更新逻辑

pkg/manager/internal.go, pkg/manager/manager.go
=> pref(manager): 优化Manager接口添加设置server

pkg/manager/manager.go
=> pref(manager): 优化Manager初始化

internal/msg/api/http/model/model.go, internal/msg/interface/http/msg.go, internal/msg/service/user.go
=> pref(msg): 调整获取对话落后消息接口响应参数

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/msg/api/http/model/model.go, internal/msg/interface/grpc/msg_grpc.go, internal/msg/interface/http/http.go, internal/msg/interface/http/msg.go, internal/msg/service/group.go, pkg/code/svc_code.go
=> fix(relation):调整设置群聊消息已读接口逻辑

internal/msg/infrastructure/persistence/msg_repository.go
=> fix(msg): 修复群聊获取未读消息失败

internal/group/infrastructure/persistence/group_repository.go, internal/group/service/group.go, internal/msg/interface/grpc/group_msg_grpc.go, internal/relation/infrastructure/persistence/group_join_request_repository.go, internal/relation/infrastructure/persistence/group_relation_repository.go, internal/relation/interface/grpc/group_grpc.go, internal/relation/interface/grpc/group_join_request_grpc.go, internal/relation/service/group.go, pkg/utils/util.go
=> fix(group):修复无法退出群聊

deploy/docker/docker-compose.yaml
=> fix:调整docker-compose文件

pkg/manager/internal.go
=> fix(manager): 修复manager未设置健康检查

deploy/docker/docker-compose.yaml, internal/push/connect/ws.go, pkg/long_conn/ws/ws.go
=> fix:修改docker-compose文件

cmd/push/main.go, internal/group/service/group.go, internal/relation/service/group.go, pkg/db/mysql.go
=> fix:修复无法获取群聊信息，修复无法申请加入群聊

cmd/push/main.go, internal/user/service/user.go
=> fix:调整push读取配置中心默认位置

internal/msg/api/http/model/model.go, internal/msg/service/group.go, internal/msg/service/user.go
=> fix:修改已读消息推送字段

internal/msg/service/user.go
=> fix:修复设置已读后对话列表lastMessage未更新

internal/admin/Makefile, internal/group/Makefile, internal/live/Makefile, internal/msg/Makefile, internal/push/Makefile, internal/storage/Makefile, internal/user/Makefile, pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> perf(manager make): 优化keepalive间隔、make

pkg/manager/server/grpc.go, pkg/manager/server/http.go
=> perf(manager): 优化服务取消注册逻辑

docs/swagger.json, docs/swagger.yaml, internal/relation/api/http/model/model.go
=> pref(relation): 设置好友备注可以为空

internal/relation/interface/grpc/user.go
=> pref(relation): 优化用户关系缓存

pkg/cache/relation_user.go
=> pref(cache): 优化用户关系缓存

internal/group/service/group.go
=> pref(group): 优化创建群聊参数判断和错误响应

internal/group/service/group.go
=> fix(group): 修复创建群聊关系判断

internal/msg/infrastructure/persistence/msg_repository.go
=> fix(msg): 修复因为中文占位符导致的sql错误

cmd/admin/main.go, cmd/gateway/main.go, cmd/group/main.go, cmd/live/main.go, cmd/msg/main.go, cmd/push/main.go, cmd/relation/main.go, cmd/storage/main.go, cmd/user/main.go, deploy/docker/docker-compose.yaml
=> deploy(compose): 优化compose启动参数

build/main.go, internal/admin/interface/http/http.go, internal/group/interface/http/http.go, internal/group/service/group.go, internal/live/interface/http/http.go, internal/live/service/user.go, internal/msg/infrastructure/persistence/msg_repository.go, internal/msg/interface/http/http.go, internal/msg/service/group.go, internal/msg/service/service.go, internal/msg/service/user.go, internal/push/interface/http/http.go, internal/push/service/service.go, internal/relation/interface/grpc/grpc.go, internal/relation/interface/http/group.go, internal/relation/interface/http/http.go, internal/relation/service/group.go, internal/relation/service/user.go, internal/storage/interface/http/http.go, internal/user/interface/http/http.go, internal/user/service/user.go, pkg/encryption/encryption.go, pkg/http/middleware/admin_middleware.go, pkg/http/middleware/auth_middleware.go, pkg/http/middleware/encryption_middleware.go, pkg/utils/http/http.go
=> fix:修复对话列表群聊的last_message一直为空,修复获取群聊公告异常

internal/relation/api/http/model/model.go, internal/relation/service/group.go, internal/relation/service/user.go
=> feat:获取好友申请，群聊申请添加create_at字段

internal/group/service/group.go, internal/relation/interface/grpc/dialog.go, internal/relation/interface/grpc/group.go, internal/relation/interface/grpc/group_join_request.go, internal/relation/interface/grpc/grpc.go, internal/relation/interface/grpc/user.go, internal/relation/interface/grpc/user_friend_request.go, internal/relation/interface/http/user.go, internal/relation/service/user.go, internal/user/infrastructure/persistence/user_login_repository.go, internal/user/interface/grpc/user_login_grpc.go, internal/user/service/user.go, pkg/cache/relation_user.go, pkg/utils/http/http.go
=> pref(relation): 优化关系缓存

internal/admin/service/admin.go, internal/msg/service/user.go, internal/relation/service/group.go, internal/user/service/user.go, pkg/email/smtp/smtp.go, pkg/long_conn/ws/ws.go
=> fix:完善todo

internal/admin/service/admin.go, internal/group/service/group.go, internal/live/service/group.go, internal/live/service/user.go, internal/msg/service/group.go, internal/msg/service/user.go, internal/relation/interface/grpc/group.go, internal/relation/interface/grpc/group_join_request.go, internal/relation/interface/grpc/grpc.go, internal/relation/interface/http/group.go, internal/relation/service/group.go, internal/relation/service/service.go, internal/relation/service/user.go, internal/user/service/user.go, pkg/cache/relation_user.go
=> pref(relation): 添加群聊关系缓存，优化推送错误处理，修复重复群聊申请

internal/relation/interface/grpc/group.go, pkg/cache/relation_group.go
=> pref(relation): 添加群聊关系缓存

internal/relation/api/http/model/model.go, internal/relation/infrastructure/persistence/user_friend_request_repository.go, internal/relation/interface/grpc/group.go, internal/relation/interface/grpc/group_join_request.go, internal/relation/interface/grpc/user.go, internal/relation/interface/http/group.go, internal/relation/service/group.go, internal/relation/service/user.go, pkg/cache/relation_group.go, pkg/config/config.go, pkg/discovery/consul.go, pkg/manager/manager.go
=> pref(relation): 优化群聊关系缓存

internal/user/interface/grpc/grpc.go, internal/user/service/user.go, pkg/cache/cache.go, pkg/cache/relation_user.go
=> pref(user): 添加用户缓存

internal/msg/api/grpc/v1/group_msg_read_grpc.pb.go, internal/msg/api/grpc/v1/msg_grpc.pb.go, internal/msg/infrastructure/persistence/msg_repository.go, internal/msg/interface/grpc/grpc.go, internal/msg/interface/grpc/msg_grpc.go
=> fix(msg): 添加消息缓存

pkg/manager/internal.go
=> fix(manager): 修复重载逻辑

pkg/cache/group.go, pkg/cache/msg.go, pkg/cache/relation_dialog.go
=> feat(cache): 消息、群里、关系对话缓存

internal/relation/service/dialog.go
=> fix:关闭或打开对话删除之前的缓存

internal/push/service/ws.go, pkg/msg_queue/rabbit_mq.go
=> fix:修复离线推送新设备登录消息无法正常推送问题

build/main.go, internal/admin/interface/http/http.go, internal/group/interface/http/http.go, internal/live/interface/http/http.go, internal/msg/interface/http/http.go, internal/push/interface/http/http.go, internal/push/interface/http/push.go, internal/push/service/service.go, internal/push/service/ws.go, internal/relation/interface/http/http.go, internal/storage/interface/http/http.go, internal/user/interface/http/http.go, pkg/constants/constants.go, pkg/encryption/encryption.go, pkg/http/middleware/auth_middleware.go, pkg/http/middleware/encryption_middleware.go
=> pref(enc): 优化enc逻辑

internal/group/interface/http/group.go, internal/relation/service/group.go
=> fix:优化加入群聊人数限制

internal/relation/service/group.go
=> fix:邀请加入群聊，申请加入群聊添加群聊类型限制

internal/msg/service/user.go, internal/push/connect/index.go, internal/push/service/ws.go
=> fix:优化ws逻辑

internal/msg/service/user.go, internal/push/connect/index.go, internal/user/service/user.go, pkg/long_conn/ws/ws.go
=> fix:优化登录推送逻辑

internal/group/service/group.go
=> fix:调整解散群聊逻辑(只有群主可以解散)

internal/msg/service/user.go
=> fix:修复获取群聊对话落后消息没有已读字段

internal/msg/interface/http/msg.go, internal/relation/interface/http/group.go, internal/relation/interface/http/user.go
=> fix:调整分页接口逻辑，设置默认值

internal/msg/infrastructure/persistence/msg_repository.go, internal/msg/interface/grpc/msg_grpc.go
=> fix:调整获取对话消息排序

internal/user/infrastructure/persistence/user_login_repository.go, internal/user/interface/grpc/user_login_grpc.go
=> fix:修复登录时last_login_time一直无变化

internal/push/interface/grpc/push_grpc.go, internal/push/service/ws.go, internal/user/service/service.go, pkg/msg_queue/rabbit_mq.go
=> fix:调整rabbitMQ离线推送逻辑

internal/user/infrastructure/persistence/user_login_repository.go, internal/user/interface/grpc/user_login_grpc.go, internal/user/service/user.go
=> fix:调整登录接口逻辑

pkg/discovery/client.go
=> feat(group): 优化ddd结构

pkg/long_conn/ws/ws.go
=> fix:调整websocket推送逻辑

internal/group/app/command/create_group.go
=> fix(group): 修复群聊限制未设置

internal/relation/interface/grpc/group.go
=> fix(relation): 修复群聊申请列表缓存未更新

internal/user/service/user.go
=> fix:修复推送新设备登录时没有driverId

pkg/cache/push.go
=> fix:优化退出登录接口逻辑

internal/live/domain/live/live.go, internal/live/domain/live/live_repository.go
=> pref(live): 优化通话服务ddd结构和http接口定义代码逻辑

internal/user/infrastructure/persistence/user_login_mysql_repository.go
=> fix(user): 修复未复制登录记录id导致的登录失败

internal/user/service/user.go
=> fix:修复新设备推送没有ip地址

internal/user/infrastructure/persistence/user_login_mysql_repository.go, internal/user/service/user.go
=> fix:修复用户登录查询缓存时出现问题

internal/push/interface/http/http.go, internal/push/interface/http/push.go
=> fix:优化socket事件注册

internal/relation/infra/persistence/group_relation_mysql_repository.go
=> pref(group): 完善群聊回滚

internal/relation/domain/relation/user.go, internal/relation/domain/relation/user_friend_request.go, internal/relation/interface/grpc/grpc.go, internal/relation/interface/grpc/user_friend_request.go, internal/relation/service/user.go
=> pref(relation): 被拉黑了对方接受不到任何消息

internal/relation/interface/grpc/user_friend_request.go, internal/relation/service/user.go
=> fix(relation): 修复因为黑名单判断逻辑导致的添加好友失败

internal/relation/interface/grpc/user_friend_request.go
=> fix(relation): 修复拒绝请求后未把对方的请求设置为拒绝

internal/relation/infra/persistence/group_relation_mysql_repository.go, internal/relation/interface/grpc/user_friend_request.go
=> fix(relation): 删除多余的model字段

internal/group/app/query/search_group.go
=> pref(group msg): 删除group旧的service，添加搜索群聊，用户消息添加条件查询

pkg/utils/jwt.go
=> pref(user): 添加从环境变量读取jwtsecret

Makefile
=> fix:调整makefile文件

Makefile, internal/admin/app/service/admin/service.go, internal/admin/domain/service/admin.go, internal/admin/infra/persistence/admin_repository.go, internal/admin/interfaces/http/http.go, internal/msg/api/http/v1/msg.yaml, internal/user/api/http/v1/user.yaml
=> fix:修复admin无法正常初始化

.github/workflows/docker_admin.yml, .github/workflows/docker_gateway.yml, .github/workflows/docker_group_service.yml, .github/workflows/docker_live_service.yml, .github/workflows/docker_msg_service.yml, .github/workflows/docker_push_service.yml, .github/workflows/docker_relation_service.yml, .github/workflows/docker_storage_service.yml, .github/workflows/docker_user_service.yml, Makefile, internal/admin/Makefile, internal/group/Makefile, internal/live/Makefile, internal/msg/Makefile, internal/push/Makefile, internal/push/api/grpc/v1/push.pb.go, internal/push/api/grpc/v1/push_grpc.pb.go, internal/relation/Makefile, internal/storage/Makefile, internal/user/Makefile
=> pref(build): 更新基础设施文件

.github/workflows/docker_admin.yml, .github/workflows/docker_gateway.yml, .github/workflows/docker_group_service.yml, .github/workflows/docker_live_service.yml, .github/workflows/docker_msg_service.yml, .github/workflows/docker_push_service.yml, .github/workflows/docker_relation_service.yml, .github/workflows/docker_storage_service.yml, .github/workflows/docker_user_service.yml
=> pref(build): 更新action checkout node版本

internal/relation/interfaces/dialog.go, internal/relation/interfaces/group.go, internal/relation/interfaces/group_announcement.go, internal/relation/interfaces/http.go, internal/relation/interfaces/user.go
=> chore(relation): 遗漏的文件

internal/relation/infra/persistence/db.go, internal/relation/infra/persistence/dialog_mysql_repository.go, internal/relation/infra/persistence/dialog_user_mysql_repository.go, internal/relation/infra/persistence/group_announcement_mysql_repository.go, internal/relation/infra/persistence/group_join_request_mysql_repository.go, internal/relation/infra/persistence/group_relation_mysql_repository.go, internal/relation/infra/persistence/po/base.go, internal/relation/infra/persistence/user_friend_request_mysql_repository.go, internal/relation/infra/persistence/user_relation_mysql_repository.go
=> pref(relation): 优化po和converter

internal/relation/app/command/add_blacklist.go, internal/relation/domain/service/dialog.go, internal/relation/domain/service/user.go, internal/relation/service/application.go
=> pref(relation): 添加黑名单后将用户对话隐藏

internal/relation/infra/persistence/converter/dialog.go, internal/relation/infra/persistence/converter/group_announcement.go, internal/relation/infra/persistence/converter/group_join_request.go, internal/relation/infra/persistence/converter/group_relation.go, internal/relation/infra/persistence/converter/user_friend_request.go, internal/relation/infra/persistence/converter/user_relation.go, internal/relation/infra/persistence/po/dialog.go, internal/relation/infra/persistence/po/group_announcement.go, internal/relation/infra/persistence/po/group_join_request.go, internal/relation/infra/persistence/po/group_relation.go, internal/relation/infra/persistence/po/user_friend_request.go, internal/relation/infra/persistence/po/user_relation.go
=> chore(relation): 遗留文件

internal/relation/app/command/add_friend.go, internal/relation/domain/service/user.go
=> pref(relation): 优化添加好友提示信息

go.mod, go.sum, internal/relation/interfaces/grpc/user.go, internal/user/app/command/user_register.go
=> fix(relation user): 修复用户不存在的处理

deploy/docker/docker-compose.yaml
=> deploy(compose): 注释hipush

docs/coss.yaml
=> fix(docs):合并api文档

docs/coss.yaml, internal/admin/app/service/admin/admin.go, internal/user/api/http/v1/openapi.gen.go, internal/user/api/http/v1/openapi.types.go, internal/user/api/http/v1/user.yaml, internal/user/app/app.go, internal/user/app/command/generate_qrcode.go, internal/user/app/command/sso_login.go, internal/user/app/command/update_avatar.go, internal/user/app/command/update_qrcode.go, internal/user/app/query/get_qrcode.go, internal/user/cache/cache.go, internal/user/domain/entity/qrcode.go, internal/user/infra/remote/storage.go, internal/user/interfaces/http/user.go, internal/user/service/application.go, pkg/storage/minio/minio.go, pkg/storage/storage.go, pkg/utils/qr/qr.go
=> feat:添加扫码登录相关接口

internal/user/app/command/user_register.go
=> fix(user): 修复注册时未判断用户邮箱是否注册

internal/relation/app/query/list_friend_request.go
=> fix(relation): 解决了由于协程执行不同步导致的好友请求列表数据乱序问题
